spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: siteadmin
    driverClassName: org.postgresql.Driver
#    initialization-mode: always
    platform: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
